# Generated by Django 4.0.1 on 2022-01-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('pos', models.CharField(choices=[('SF', 'Small Forward'), ('C', 'Center'), ('PF', 'Power Forward'), ('PG', 'Point Guard'), ('SG', 'Shooting Guard')], max_length=100)),
                ('height', models.CharField(max_length=100)),
            ],
        ),
    ]
